name: Deploy to Google Cloud Functions on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/242908451593/locations/global/workloadIdentityPools/example-pool/providers/example-gh-provider'
          service_account: 'test-storage-sa@recommeddit.iam.gserviceaccount.com'

      - id: 'deploy-search'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'search'
          runtime: 'python39'

      - id: 'deploy-autocomplete'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'auto_suggest'
          runtime: 'python39'